apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./k8s/*
build:
  local:
    push: false
  artifacts:
    - image: philipjesic/auth-gateway
      context: auth-gateway
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: philipjesic/listings
      context: listings
      docker:
        dockerfile: Dockerfile
      #sync:
      #  manual:
      #    - src: "src/**/*.ts"
      #      dest: .
    - image: philipjesic/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.ts'
            dest: .