apiVersion: apps/v1
kind: Deployment
metadata:
  name: bids-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bids
  template:
    metadata:
      labels:
        app: bids
    spec:
      containers:
        - name: bids
          image: philipjesic/bids
          env:
            - name: MONGO_URI
              value: mongodb://bids-mongo-srv:27017/bids
            - name: RABBITMQ_URI
              value: amqp://guest:guest@rabbitmq-srv:5672
---
apiVersion: v1
kind: Service
metadata:
  name: bids-srv
spec:
  selector:
    app: bids
  ports:
    - name: bids
      protocol: TCP
      port: 3000
      targetPort: 3000
