apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-gateway-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-gateway
  template:
    metadata:
      labels: 
        app: auth-gateway
    spec:
      containers:
        - name: auth-gateway
          image: philipjesic/auth-gateway
          env:
            - name: MONGO_URI
              value: mongodb://auth-gateway-mongo-srv:27017/auth
            #TODO: change to K8s secret
            #- name: JWT_SECRET
            #  value: test
---
apiVersion: v1
kind: Service
metadata:
  name: auth-gateway-srv
spec:
  selector:
    app: auth-gateway
  ports:
    - name: auth-gateway
      protocol: TCP
      port: 3000
      targetPort: 3000
